package br.com.serviceflow.api.controller;
import static br.com.serviceflow.api.dto.domain.DomainDtos.*; import br.com.serviceflow.api.service.DomainService; import io.swagger.v3.oas.annotations.tags.Tag; import jakarta.validation.Valid; import java.time.LocalDate; import java.util.List; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.security.oauth2.jwt.Jwt; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v2") @Tag(name="Operação") public class DomainController {
 private final DomainService s; public DomainController(DomainService s){this.s=s;} private Long e(Jwt j){return j.getClaim("companyId");}
 @PostMapping("/clientes") public ClienteOut addCliente(@AuthenticationPrincipal Jwt j,@Valid @RequestBody ClienteIn x){return s.addCliente(e(j),x);} @GetMapping("/clientes") public List<ClienteOut> clientes(@AuthenticationPrincipal Jwt j,@RequestParam(required=false) String busca){return s.clientes(e(j),busca);} @GetMapping("/clientes/{id}") public ClienteOut cliente(@AuthenticationPrincipal Jwt j,@PathVariable Long id){return s.cliente(e(j),id);}
 @PostMapping("/veiculos") public VeiculoOut addVeiculo(@AuthenticationPrincipal Jwt j,@Valid @RequestBody VeiculoIn x){return s.addVeiculo(e(j),x);} @GetMapping("/clientes/{id}/veiculos") public List<VeiculoOut> veiculos(@AuthenticationPrincipal Jwt j,@PathVariable Long id){return s.veiculos(e(j),id);}
 @PostMapping("/servicos") public ServicoOut addServico(@AuthenticationPrincipal Jwt j,@Valid @RequestBody ServicoIn x){return s.addServico(e(j),x);} @GetMapping("/servicos") public List<ServicoOut> servicos(@AuthenticationPrincipal Jwt j){return s.servicos(e(j));}
 @PostMapping("/ordens-servico") public OrdemOut addOrdem(@AuthenticationPrincipal Jwt j,@Valid @RequestBody OrdemIn x){return s.addOrdem(e(j),x);} @GetMapping("/ordens-servico/{id}") public OrdemOut ordem(@AuthenticationPrincipal Jwt j,@PathVariable Long id){return s.ordem(e(j),id);} @GetMapping("/ordens-servico") public List<OrdemOut> ordens(@AuthenticationPrincipal Jwt j,@RequestParam LocalDate dataInicial,@RequestParam LocalDate dataFinal){return s.ordens(e(j),dataInicial,dataFinal);} @PatchMapping("/ordens-servico/{id}/status") public OrdemOut status(@AuthenticationPrincipal Jwt j,@PathVariable Long id,@Valid @RequestBody StatusIn x){return s.status(e(j),id,x.status());}
 @PostMapping("/despesas") public DespesaOut addDespesa(@AuthenticationPrincipal Jwt j,@Valid @RequestBody DespesaIn x){return s.addDespesa(e(j),x);} @GetMapping("/despesas") public List<DespesaOut> despesas(@AuthenticationPrincipal Jwt j,@RequestParam LocalDate dataInicial,@RequestParam LocalDate dataFinal){return s.despesas(e(j),dataInicial,dataFinal);}
 @GetMapping("/financeiro/resumo") public FinanceiroOut financeiro(@AuthenticationPrincipal Jwt j,@RequestParam LocalDate dataInicial,@RequestParam LocalDate dataFinal){return s.financeiro(e(j),dataInicial,dataFinal);} @GetMapping("/dashboard/diario") public FinanceiroOut dashboard(@AuthenticationPrincipal Jwt j,@RequestParam LocalDate data){return s.financeiro(e(j),data,data);}
 @PutMapping("/clientes/{id}") public ClienteOut updateCliente(@AuthenticationPrincipal Jwt j,@PathVariable Long id,@Valid @RequestBody ClienteIn x){return s.updateCliente(e(j),id,x);} @DeleteMapping("/clientes/{id}") @ResponseStatus(org.springframework.http.HttpStatus.NO_CONTENT) public void deleteCliente(@AuthenticationPrincipal Jwt j,@PathVariable Long id){s.deleteCliente(e(j),id);}
 @GetMapping("/veiculos/{id}") public VeiculoOut veiculo(@AuthenticationPrincipal Jwt j,@PathVariable Long id){return s.veiculo(e(j),id);} @PutMapping("/veiculos/{id}") public VeiculoOut updateVeiculo(@AuthenticationPrincipal Jwt j,@PathVariable Long id,@Valid @RequestBody VeiculoIn x){return s.updateVeiculo(e(j),id,x);} @DeleteMapping("/veiculos/{id}") @ResponseStatus(org.springframework.http.HttpStatus.NO_CONTENT) public void deleteVeiculo(@AuthenticationPrincipal Jwt j,@PathVariable Long id){s.deleteVeiculo(e(j),id);}
 @GetMapping("/servicos/{id}") public ServicoOut servico(@AuthenticationPrincipal Jwt j,@PathVariable Long id){return s.servico(e(j),id);} @PutMapping("/servicos/{id}") public ServicoOut updateServico(@AuthenticationPrincipal Jwt j,@PathVariable Long id,@Valid @RequestBody ServicoIn x){return s.updateServico(e(j),id,x);} @DeleteMapping("/servicos/{id}") @ResponseStatus(org.springframework.http.HttpStatus.NO_CONTENT) public void deleteServico(@AuthenticationPrincipal Jwt j,@PathVariable Long id){s.deleteServico(e(j),id);}
 @PutMapping("/ordens-servico/{id}") public OrdemOut updateOrdem(@AuthenticationPrincipal Jwt j,@PathVariable Long id,@Valid @RequestBody OrdemIn x){return s.updateOrdem(e(j),id,x);} @DeleteMapping("/ordens-servico/{id}") @ResponseStatus(org.springframework.http.HttpStatus.NO_CONTENT) public void deleteOrdem(@AuthenticationPrincipal Jwt j,@PathVariable Long id){s.deleteOrdem(e(j),id);}
 @GetMapping("/despesas/{id}") public DespesaOut despesa(@AuthenticationPrincipal Jwt j,@PathVariable Long id){return s.despesa(e(j),id);} @PutMapping("/despesas/{id}") public DespesaOut updateDespesa(@AuthenticationPrincipal Jwt j,@PathVariable Long id,@Valid @RequestBody DespesaIn x){return s.updateDespesa(e(j),id,x);} @DeleteMapping("/despesas/{id}") @ResponseStatus(org.springframework.http.HttpStatus.NO_CONTENT) public void deleteDespesa(@AuthenticationPrincipal Jwt j,@PathVariable Long id){s.deleteDespesa(e(j),id);}
}
