package br.com.serviceflow.api.service;
import br.com.serviceflow.api.dto.auth.*; import br.com.serviceflow.api.model.*; import br.com.serviceflow.api.repository.*; import java.nio.charset.StandardCharsets; import java.security.*; import java.time.*; import java.util.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.security.authentication.BadCredentialsException; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @Transactional public class CredentialTokenService {
 private final RefreshTokenRepository rr; private final PasswordResetTokenRepository pr; private final UsuarioRepository ur; private final PasswordEncoder pe; private final TokenService ts; private final boolean expose;
 public CredentialTokenService(RefreshTokenRepository rr,PasswordResetTokenRepository pr,UsuarioRepository ur,PasswordEncoder pe,TokenService ts,@Value("${app.security.expose-reset-token:false}") boolean expose){this.rr=rr;this.pr=pr;this.ur=ur;this.pe=pe;this.ts=ts;this.expose=expose;}
 public String issue(Usuario u){String raw=random();RefreshToken t=new RefreshToken();t.setUsuario(u);t.setTokenHash(hash(raw));t.setExpiraEm(LocalDateTime.now().plusDays(30));t.setRevogado(false);t.setCriadoEm(LocalDateTime.now());rr.save(t);return raw;}
 public LoginResponse refresh(String raw,UsuarioMapper mapper){RefreshToken old=rr.findByTokenHash(hash(raw)).filter(t->!t.getRevogado()&&t.getExpiraEm().isAfter(LocalDateTime.now())).orElseThrow(()->new BadCredentialsException("Refresh token inválido ou expirado"));old.setRevogado(true);Usuario u=old.getUsuario();return new LoginResponse(ts.createAccessToken(u),issue(u),"Bearer",ts.expiresInSeconds(),mapper.toDto(u));}
 public void logout(String raw){rr.findByTokenHash(hash(raw)).ifPresent(t->t.setRevogado(true));}
 public MessageResponse forgot(String email){String raw=null;Optional<Usuario> found=ur.findByEmailIgnoreCase(email.trim());if(found.isPresent()){raw=random();PasswordResetToken t=new PasswordResetToken();t.setUsuario(found.get());t.setTokenHash(hash(raw));t.setExpiraEm(LocalDateTime.now().plusMinutes(30));t.setCriadoEm(LocalDateTime.now());pr.save(t);}return new MessageResponse("Se o e-mail estiver cadastrado, as instruções de recuperação serão enviadas",expose?raw:null);}
 public void reset(ResetPasswordRequest x){PasswordResetToken t=pr.findByTokenHash(hash(x.token())).filter(v->v.getUtilizadoEm()==null&&v.getExpiraEm().isAfter(LocalDateTime.now())).orElseThrow(()->new BadCredentialsException("Token de recuperação inválido ou expirado"));t.getUsuario().setSenhaHash(pe.encode(x.newPassword()));t.setUtilizadoEm(LocalDateTime.now());revokeAll(t.getUsuario().getId());}
 public void change(Usuario u,ChangePasswordRequest x){if(!pe.matches(x.currentPassword(),u.getSenhaHash()))throw new BadCredentialsException("Senha atual inválida");u.setSenhaHash(pe.encode(x.newPassword()));u.setTrocaSenhaObrigatoria(false);ur.save(u);revokeAll(u.getId());}
 public void revokeAllSessions(Long id){revokeAll(id);}
 private void revokeAll(Long id){rr.findByUsuarioIdAndRevogadoFalse(id).forEach(t->t.setRevogado(true));}
 private String random(){byte[] b=new byte[32];new SecureRandom().nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);} private String hash(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}
